name: mvp-test-harness
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The ${{ github.ref }} branch job was automatically triggered by a ${{ github.event_name }} event"
      - name: Clone repo
        uses: actions/checkout@v2
      - name: E2E
        uses: cypress-io/github-action@v2
        with:
          start: npm run start
          wait-on: http://localhost:4200
          wait-on-timeout: 180
      - name: Lint
        run: |
          npm run lint
      - name: Format
        run: |
          npm run format:check
      - name: Test
        run: |
          npm run test
      - name: Upload E2E videos
        uses: actions/upload-artifact@master
        if: success()
        with:
          name: videos
          path: cypress/videos
      - name: Upload E2E screenshots
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots
      - run: echo "CI completed with status ${{ job.status }}"
