name: End-to-end tests
on: [push]
jobs:
  end-to-end-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Rosie
        uses: actions/checkout@v2

      # https://stackoverflow.com/a/61350264
      - name: Make Github use https for node
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://".insteadOf git://

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ hashFiles('package-lock.json') }}

      - name: Run cypress test suite
        uses: cypress-io/github-action@v2
        with:
          start: npm run start
          wait-on: 'http://localhost:4200'
          wait-on-timeout: 60
          browser: chrome
          headless: true

      - name: Upload videos
        uses: actions/upload-artifact@master
        if: success()
        with:
          name: videos
          path: cypress/videos

      - name: Upload screenshots
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots
